baseurl = "https://andrewsonin.github.io"
languageCode = "en-us"
title = "Andrew Sonin — Personal Website"
theme = "hugo-xmin"
googleAnalytics = "G-R9374K3FFD"
ignoreFiles = [ "_cache$" ]
canonifyURLs = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
name = "About"
url = ""
weight = 1

[[menu.main]]
name = "Blog"
url = "blog/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[params]
description = "Personal website of Andrew Sonin"
footer = '<address style="font-style: normal;">&copy; Andrew Sonin 2025 — {Year} | <a href="https://t.me/sonin" rel="author me noreferrer external" target="_blank">Telegram</a> | <a href="https://github.com/andrewsonin" rel="author me noreferrer external" target="_blank">GitHub</a> | <a href="https://www.linkedin.com/in/andrewsonin" rel="author me noreferrer external" target="_blank">LinkedIn</a> | <a href="mailto:sonin.cel@gmail.com" rel="author me nofollow">E-mail</a></address>'
mainSections = ["blog"]
[params.urls]
gravatar = "https://gravatar.com/avatar/5838c16fa65bbc16b5eedc94e9369d7d?s=800"
github = "https://github.com/andrewsonin"
[params.staticPaths]
avatar = "avatar.jpg"
[params.authors]
[params.authors.default]
name = "Andrew Sonin"
mail = "sonin.cel@gmail.com"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
